# Generated by Django 5.0.3 on 2024-03-24 16:14

import django.core.validators
import django.db.models.deletion
import django_ckeditor_5.fields
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30, unique=True, verbose_name='Descripción')),
                ('bloquea', models.BooleanField(default=False, help_text='Determina si bloquea modificaciones', verbose_name='Bloquea modificaciones')),
                ('vigente', models.BooleanField(default=True, verbose_name='Vigente')),
                ('actualizacion', models.DateTimeField(auto_now=True, verbose_name='Actualización')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalComentario',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('descripcion', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Descripción')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical comentario',
                'verbose_name_plural': 'historical comentarios',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalEstado',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('descripcion', models.CharField(db_index=True, max_length=30, verbose_name='Descripción')),
                ('bloquea', models.BooleanField(default=False, help_text='Determina si bloquea modificaciones', verbose_name='Bloquea modificaciones')),
                ('vigente', models.BooleanField(default=True, verbose_name='Vigente')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical estado',
                'verbose_name_plural': 'historical estados',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProyecto',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('nombre', models.CharField(db_index=True, max_length=90, verbose_name='Nombre')),
                ('descripcion', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Descripción')),
                ('finicio', models.DateField(verbose_name='Fecha Inicio')),
                ('ffin', models.DateField(verbose_name='Fecha Fin')),
                ('publico', models.BooleanField(default=True, help_text='Define si el proyecto es visible para todos los usuarios', verbose_name='Público')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('estado', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='seguimiento.estado', verbose_name='Estado')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical proyecto',
                'verbose_name_plural': 'historical proyectos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProyecto_Fase',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('descripcion', models.CharField(blank=True, max_length=180, verbose_name='Descripción')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical proyecto_ fase',
                'verbose_name_plural': 'historical proyecto_ fases',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProyecto_Meta',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('descripcion', models.CharField(blank=True, max_length=180, verbose_name='Descripción')),
                ('alcanzado', models.BooleanField(default=False, verbose_name='Alcanzado')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical proyecto_ meta',
                'verbose_name_plural': 'historical proyecto_ metas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProyecto_Objetivo',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('descripcion', models.CharField(blank=True, max_length=180, verbose_name='Descripción')),
                ('alcanzado', models.BooleanField(default=False, verbose_name='Alcanzado')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical proyecto_ objetivo',
                'verbose_name_plural': 'historical proyecto_ objetivos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProyecto_Tarea',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('descripcion', models.CharField(blank=True, max_length=180, verbose_name='Descripción')),
                ('complejidad', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Complejidad')),
                ('finalizado', models.BooleanField(default=False, verbose_name='Finalizado')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical proyecto_ tarea',
                'verbose_name_plural': 'historical proyecto_ tareas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=90, unique=True, verbose_name='Nombre')),
                ('descripcion', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Descripción')),
                ('creacion', models.DateField(auto_now_add=True, verbose_name='Creación')),
                ('actualizacion', models.DateTimeField(auto_now=True, verbose_name='Actualización')),
                ('finicio', models.DateField(verbose_name='Fecha Inicio')),
                ('ffin', models.DateField(verbose_name='Fecha Fin')),
                ('publico', models.BooleanField(default=True, help_text='Define si el proyecto es visible para todos los usuarios', verbose_name='Público')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='seguimiento.estado', verbose_name='Estado')),
            ],
            options={
                'permissions': [('proyect_admin', 'Permite ver todos los proyectos, sean publicos o privados')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalProyecto_Usuario',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('proyecto', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='seguimiento.proyecto', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'historical proyecto_ usuario',
                'verbose_name_plural': 'historical proyecto_ usuarios',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Descripción')),
                ('creacion', models.DateField(auto_now_add=True, verbose_name='Creación')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='seguimiento.proyecto', verbose_name='Proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto_Fase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('correlativo', models.PositiveSmallIntegerField(verbose_name='Correlativo')),
                ('descripcion', models.CharField(blank=True, max_length=180, verbose_name='Descripción')),
                ('creacion', models.DateField(auto_now_add=True, verbose_name='Creación')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='seguimiento.proyecto', verbose_name='Proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto_Meta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=180, verbose_name='Descripción')),
                ('alcanzado', models.BooleanField(default=False, verbose_name='Alcanzado')),
                ('creacion', models.DateField(auto_now_add=True, verbose_name='Creación')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='seguimiento.proyecto', verbose_name='Proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto_Objetivo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=180, verbose_name='Descripción')),
                ('alcanzado', models.BooleanField(default=False, verbose_name='Alcanzado')),
                ('creacion', models.DateField(auto_now_add=True, verbose_name='Creación')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='seguimiento.proyecto', verbose_name='Proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto_Tarea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=180, verbose_name='Descripción')),
                ('complejidad', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Complejidad')),
                ('creacion', models.DateField(auto_now_add=True, verbose_name='Creación')),
                ('finalizado', models.BooleanField(default=False, verbose_name='Finalizado')),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='seguimiento.proyecto_fase', verbose_name='Fase')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto_Usuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='seguimiento.proyecto', verbose_name='Proyecto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.AddConstraint(
            model_name='proyecto_fase',
            constraint=models.UniqueConstraint(fields=('correlativo', 'proyecto'), name='unq_pf_correlativo_proyecto'),
        ),
        migrations.AddConstraint(
            model_name='proyecto_fase',
            constraint=models.UniqueConstraint(fields=('descripcion', 'proyecto'), name='unq_pf_descripcion_proyecto'),
        ),
    ]
