# Generated by Django 5.0.1 on 2024-03-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='tipo',
            field=models.CharField(choices=[('P', 'Proyecto'), ('T', 'Tarea'), ('F', 'Fase')], default='P', max_length=1, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='historicalcomentario',
            name='tipo',
            field=models.CharField(choices=[('P', 'Proyecto'), ('T', 'Tarea'), ('F', 'Fase')], default='P', max_length=1, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='historicalproyecto',
            name='enlace_cloud',
            field=models.URLField(blank=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='enlace_cloud',
            field=models.URLField(blank=True, verbose_name='URL'),
        ),
    ]
