# Generated by Django 5.0.3 on 2024-03-26 22:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0002_comentario_tipo_historicalcomentario_tipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='proyecto',
        ),
        migrations.AddField(
            model_name='comentario',
            name='obj_id',
            field=models.CharField(blank=True, default='', max_length=36, verbose_name='Objeto'),
        ),
        migrations.AddField(
            model_name='historicalcomentario',
            name='obj_id',
            field=models.CharField(blank=True, default='', max_length=36, verbose_name='Objeto'),
        ),
        migrations.AlterField(
            model_name='historicalproyecto_tarea',
            name='complejidad',
            field=models.PositiveSmallIntegerField(default=1, help_text='Complejidad de 1 a 100', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Complejidad'),
        ),
        migrations.AlterField(
            model_name='historicalproyecto_tarea',
            name='finalizado',
            field=models.PositiveSmallIntegerField(default=0, help_text='Porcentaje de activdad completada de 0 - 100%', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='% Completado'),
        ),
        migrations.AlterField(
            model_name='proyecto_tarea',
            name='complejidad',
            field=models.PositiveSmallIntegerField(default=1, help_text='Complejidad de 1 a 100', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Complejidad'),
        ),
        migrations.AlterField(
            model_name='proyecto_tarea',
            name='finalizado',
            field=models.PositiveSmallIntegerField(default=0, help_text='Porcentaje de activdad completada de 0 - 100%', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='% Completado'),
        ),
    ]
