# Generated by Django 5.0.1 on 2024-04-09 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0003_origen_proyecto_pm_proyecto_tipo_proyecto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'permissions': [('proyect_admin', 'Ver todos los proyectos y agregar usuarios')]},
        ),
    ]
