# Generated by Django 5.0.1 on 2024-04-12 14:32

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0004_alter_proyecto_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproyecto_fase',
            name='descripcion',
            field=models.CharField(max_length=180, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='historicalproyecto_tarea',
            name='descripcion',
            field=models.CharField(max_length=180, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='proyecto_fase',
            name='descripcion',
            field=models.CharField(max_length=180, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='proyecto_tarea',
            name='descripcion',
            field=models.CharField(max_length=180, verbose_name='Descripción'),
        ),
        migrations.CreateModel(
            name='HistoricalProyecto_Actividad',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('creacion', models.DateField(blank=True, editable=False, verbose_name='Creación')),
                ('descripcion', models.CharField(max_length=180, verbose_name='Descripción')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical proyecto_ actividad',
                'verbose_name_plural': 'historical proyecto_ actividads',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Proyecto_Actividad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creacion', models.DateField(auto_now_add=True, verbose_name='Creación')),
                ('descripcion', models.CharField(max_length=180, verbose_name='Descripción')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='seguimiento.proyecto_tarea', verbose_name='Tarea')),
            ],
        ),
    ]
