# Generated by Django 5.0.1 on 2024-04-15 16:41

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0005_alter_historicalproyecto_fase_descripcion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproyecto_fase',
            name='cerrado',
            field=models.BooleanField(default=False, help_text='Cierra de forma definitiva la fase (impide asignar nuevas tareas)', verbose_name='Cerrado'),
        ),
        migrations.AddField(
            model_name='proyecto_fase',
            name='cerrado',
            field=models.BooleanField(default=False, help_text='Cierra de forma definitiva la fase (impide asignar nuevas tareas)', verbose_name='Cerrado'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='tipo',
            field=models.CharField(choices=[('P', 'Proyecto'), ('T', 'Tarea'), ('F', 'Fase'), ('A', 'Activdad')], default='P', max_length=1, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='historicalcomentario',
            name='tipo',
            field=models.CharField(choices=[('P', 'Proyecto'), ('T', 'Tarea'), ('F', 'Fase'), ('A', 'Activdad')], default='P', max_length=1, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='HistoricalProyecto_Pendiente',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('creacion', models.DateField(blank=True, editable=False, verbose_name='Creación')),
                ('actualizacion', models.DateField(blank=True, editable=False, verbose_name='Actualizacion')),
                ('descripcion', models.CharField(max_length=180, verbose_name='Descripción')),
                ('responsable', models.CharField(max_length=180, verbose_name='Responsable')),
                ('finalizado', models.BooleanField(default=False, verbose_name='Finalizado')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical proyecto_ pendiente',
                'verbose_name_plural': 'historical proyecto_ pendientes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Proyecto_Pendiente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creacion', models.DateField(auto_now_add=True, verbose_name='Creación')),
                ('actualizacion', models.DateField(auto_now=True, verbose_name='Actualizacion')),
                ('descripcion', models.CharField(max_length=180, verbose_name='Descripción')),
                ('responsable', models.CharField(max_length=180, verbose_name='Responsable')),
                ('finalizado', models.BooleanField(default=False, verbose_name='Finalizado')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='seguimiento.proyecto', verbose_name='Proyecto')),
            ],
        ),
    ]
