# Generated by Django 5.0.1 on 2024-04-16 15:06

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0006_historicalproyecto_fase_cerrado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproyecto_actividad',
            name='creacion',
        ),
        migrations.RemoveField(
            model_name='historicalproyecto_pendiente',
            name='actualizacion',
        ),
        migrations.RemoveField(
            model_name='historicalproyecto_pendiente',
            name='creacion',
        ),
        migrations.AddField(
            model_name='historicalproyecto_pendiente',
            name='resolucion',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Resolución'),
        ),
        migrations.AddField(
            model_name='proyecto_actividad',
            name='actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualización'),
        ),
        migrations.AddField(
            model_name='proyecto_meta',
            name='actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualización'),
        ),
        migrations.AddField(
            model_name='proyecto_objetivo',
            name='actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualización'),
        ),
        migrations.AddField(
            model_name='proyecto_pendiente',
            name='resolucion',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Resolución'),
        ),
        migrations.AddField(
            model_name='proyecto_tarea',
            name='actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualización'),
        ),
        migrations.AlterField(
            model_name='historicalproyecto_pendiente',
            name='finalizado',
            field=models.BooleanField(default=False, verbose_name='Resuelto'),
        ),
        migrations.AlterField(
            model_name='proyecto_pendiente',
            name='finalizado',
            field=models.BooleanField(default=False, verbose_name='Resuelto'),
        ),
        migrations.DeleteModel(
            name='HistoricalComentario',
        ),
    ]
