# Generated by Django 5.0.1 on 2024-04-26 13:50

import django.core.validators
import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0007_remove_historicalproyecto_actividad_creacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto_pendiente',
            name='proyecto',
        ),
        migrations.AlterModelOptions(
            name='proyecto',
            options={'permissions': [('proyect_admin', 'Ver todos los proyectos y agregar usuarios'), ('reportes', 'Permite visualizar las opciones de reportería')]},
        ),
        migrations.RemoveField(
            model_name='historicalproyecto_tarea',
            name='finalizado',
        ),
        migrations.RemoveField(
            model_name='proyecto_tarea',
            name='finalizado',
        ),
        migrations.AddField(
            model_name='historicalproyecto_actividad',
            name='finalizado',
            field=models.PositiveSmallIntegerField(default=0, help_text='Porcentaje de activdad completada de 0 - 100%', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='% Completado'),
        ),
        migrations.AddField(
            model_name='historicalproyecto_actividad',
            name='resolucion',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Resolución'),
        ),
        migrations.AddField(
            model_name='historicalproyecto_actividad',
            name='responsable',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AddField(
            model_name='proyecto_actividad',
            name='finalizado',
            field=models.PositiveSmallIntegerField(default=0, help_text='Porcentaje de activdad completada de 0 - 100%', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='% Completado'),
        ),
        migrations.AddField(
            model_name='proyecto_actividad',
            name='resolucion',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Resolución'),
        ),
        migrations.AddField(
            model_name='proyecto_actividad',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AlterField(
            model_name='estado',
            name='vigente',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='historicalestado',
            name='vigente',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.DeleteModel(
            name='HistoricalProyecto_Pendiente',
        ),
        migrations.DeleteModel(
            name='Proyecto_Pendiente',
        ),
    ]
