# Generated by Django 5.0.1 on 2024-05-09 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0008_remove_proyecto_pendiente_proyecto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproyecto_actividad',
            name='tarea',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='seguimiento.proyecto_tarea', verbose_name='Tarea'),
        ),
        migrations.AddField(
            model_name='historicalproyecto_fase',
            name='proyecto',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='seguimiento.proyecto', verbose_name='Proyecto'),
        ),
        migrations.AddField(
            model_name='historicalproyecto_meta',
            name='proyecto',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='seguimiento.proyecto', verbose_name='Proyecto'),
        ),
        migrations.AddField(
            model_name='historicalproyecto_objetivo',
            name='proyecto',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='seguimiento.proyecto', verbose_name='Proyecto'),
        ),
        migrations.AddField(
            model_name='historicalproyecto_tarea',
            name='fase',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='seguimiento.proyecto_fase', verbose_name='Fase'),
        ),
        migrations.AlterField(
            model_name='proyecto_actividad',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
    ]
