# Generated by Django 5.0.1 on 2024-05-14 15:49

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0009_historicalproyecto_actividad_creacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProyecto_Etiqueta',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('descripcion', models.CharField(blank=True, max_length=180, verbose_name='Descripción')),
                ('vigente', models.BooleanField(default=True, verbose_name='Estado')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='seguimiento.proyecto', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'historical proyecto_ etiqueta',
                'verbose_name_plural': 'historical proyecto_ etiquetas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Proyecto_Etiqueta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=180, verbose_name='Descripción')),
                ('creacion', models.DateField(auto_now_add=True, verbose_name='Creación')),
                ('actualizacion', models.DateTimeField(auto_now=True, verbose_name='Actualización')),
                ('vigente', models.BooleanField(default=True, verbose_name='Estado')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimiento.proyecto', verbose_name='Proyecto')),
            ],
        ),
        migrations.AddField(
            model_name='proyecto_tarea',
            name='etiqueta',
            field=models.ManyToManyField(blank=True, to='seguimiento.proyecto_etiqueta', verbose_name='etiqueta'),
        ),
        migrations.AddConstraint(
            model_name='proyecto_etiqueta',
            constraint=models.UniqueConstraint(fields=('proyecto', 'descripcion'), name='unq_pe_proyecto_descripcion'),
        ),
    ]
